version: "3.1"
services:
  mongo:
    image: mongo:4.4
    restart: always
  backend:
    image: backend
    build: ./backend
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - 9000:9000
  frontend:
    image: frontend
    build: ./frontend
    restart: always
    stdin_open: true
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 5173:5173
