version: "3.1"
services:
  mongo:
    image: mongo:4.4
    networks:
      - net-mapper
    restart: always
  backend:
    image: backend
    build: ./backend
    restart: always
    networks:
      - net-mapper
    depends_on:
      - mongo
    env_file:
      - .env
  frontend:
    image: frontend
    build: ./frontend
    restart: always
    networks:
      - net-mapper
    stdin_open: true
    depends_on:
      - backend
    env_file:
      - .env
networks: 
  net-mapper:
